[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python manage.py migrate --noinput && echo 'MIGRATE_DONE' && python manage.py process_tasks --verbosity=2 2>&1"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
