name: Deploy to Railway
on:
  push:
    branches: [main]
jobs:
  report:
    name: Report deployment to Port
    runs-on: ubuntu-latest
    steps:
      - name: Report deployment to Port
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: UPSERT
          identifier: dtc-brightbean-web-${{ github.sha }}
          title: "dtc-brightbean-web @ ${{ github.sha }}"
          blueprint: deployment
          properties: |-
            {
              "createdAt": "${{ github.event.head_commit.timestamp }}",
              "deploymentStatus": "Success",
              "environment": "Production"
            }
          relations: |-
            {
              "service": "dtc-brightbean-web"
            }

